

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "ProgressBook.Reporting.Web\Web.config"
//     Connection String Name: "StudentInformation"
//     Connection String:      "Data Source=SAPC052;Initial Catalog=DASL_HTFX;User Id=dasldev;password=**zapped**;"
// ------------------------------------------------------------------------------------------------
// Database Edition       : Developer Edition (64-bit)
// Database Engine Edition: Enterprise

// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.7
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ProgressBook.Reporting.Client.Data
{

    #region Unit of work

    public interface IAdHocReportsContext : System.IDisposable
    {
        System.Data.Entity.DbSet<ReportEntityInfo> ReportEntityInfo { get; set; } // ReportEntityInfo
        System.Data.Entity.DbSet<UserReportAttribute> UserReportAttributes { get; set; } // UserReportAttribute

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();
    }

    #endregion

    #region Database context

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class AdHocReportsContext : System.Data.Entity.DbContext, IAdHocReportsContext
    {
        public System.Data.Entity.DbSet<ReportEntityInfo> ReportEntityInfo { get; set; } // ReportEntityInfo
        public System.Data.Entity.DbSet<UserReportAttribute> UserReportAttributes { get; set; } // UserReportAttribute

        static AdHocReportsContext()
        {
            System.Data.Entity.Database.SetInitializer<AdHocReportsContext>(null);
        }

        public AdHocReportsContext()
            : base("Name=StudentInformation")
        {
        }

        public AdHocReportsContext(string connectionString)
            : base(connectionString)
        {
        }

        public AdHocReportsContext(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model)
            : base(connectionString, model)
        {
        }

        public AdHocReportsContext(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection)
            : base(existingConnection, contextOwnsConnection)
        {
        }

        public AdHocReportsContext(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection)
            : base(existingConnection, model, contextOwnsConnection)
        {
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        public bool IsSqlParameterNull(System.Data.SqlClient.SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as System.Data.SqlTypes.INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == System.DBNull.Value);
        }

        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Configurations.Add(new ReportEntityInfoConfiguration());
            modelBuilder.Configurations.Add(new UserReportAttributeConfiguration());
        }

        public static System.Data.Entity.DbModelBuilder CreateModel(System.Data.Entity.DbModelBuilder modelBuilder, string schema)
        {
            modelBuilder.Configurations.Add(new ReportEntityInfoConfiguration(schema));
            modelBuilder.Configurations.Add(new UserReportAttributeConfiguration(schema));
            return modelBuilder;
        }
    }
    #endregion

    #region POCO classes

    // ReportEntityInfo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class ReportEntityInfo
    {
        public System.Guid ReportEntityId { get; set; } // ReportEntityId (Primary key)
        public System.Guid? ParentId { get; set; } // ParentId
        public string Path { get; set; } // Path (length: 1000)
        public string Name { get; set; } // Name (length: 255)
        public System.Guid? DistrictId { get; set; } // DistrictId
        public System.Guid? UserId { get; set; } // UserId
        public int IsSystemLevel { get; set; } // IsSystemLevel
        public int IsDistrictLevel { get; set; } // IsDistrictLevel
        public int IsUserLevel { get; set; } // IsUserLevel
    }

    // UserReportAttribute
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class UserReportAttribute
    {
        public System.Guid ReportEntityId { get; set; } // ReportEntityId (Primary key)
        public System.Guid DistrictId { get; set; } // DistrictId (Primary key)
        public System.Guid UserId { get; set; } // UserId (Primary key)
        public System.DateTime? LastRunDate { get; set; } // LastRunDate
        public int RunCount { get; set; } // RunCount
        public bool IsFavorite { get; set; } // IsFavorite

        public UserReportAttribute()
        {
            RunCount = 0;
            IsFavorite = false;
        }
    }

    #endregion

    #region POCO Configuration

    // ReportEntityInfo
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class ReportEntityInfoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ReportEntityInfo>
    {
        public ReportEntityInfoConfiguration()
            : this("CoreReports")
        {
        }

        public ReportEntityInfoConfiguration(string schema)
        {
            ToTable("ReportEntityInfo", schema);
            HasKey(x => x.ReportEntityId);

            Property(x => x.ReportEntityId).HasColumnName(@"ReportEntityId").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ParentId).HasColumnName(@"ParentId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.Path).HasColumnName(@"Path").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(1000);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(255);
            Property(x => x.DistrictId).HasColumnName(@"DistrictId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.IsSystemLevel).HasColumnName(@"IsSystemLevel").HasColumnType("int").IsRequired();
            Property(x => x.IsDistrictLevel).HasColumnName(@"IsDistrictLevel").HasColumnType("int").IsRequired();
            Property(x => x.IsUserLevel).HasColumnName(@"IsUserLevel").HasColumnType("int").IsRequired();
        }
    }

    // UserReportAttribute
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public class UserReportAttributeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UserReportAttribute>
    {
        public UserReportAttributeConfiguration()
            : this("CoreReports")
        {
        }

        public UserReportAttributeConfiguration(string schema)
        {
            ToTable("UserReportAttribute", schema);
            HasKey(x => new { x.ReportEntityId, x.DistrictId, x.UserId });

            Property(x => x.ReportEntityId).HasColumnName(@"ReportEntityId").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.DistrictId).HasColumnName(@"DistrictId").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.LastRunDate).HasColumnName(@"LastRunDate").HasColumnType("datetime").IsOptional();
            Property(x => x.RunCount).HasColumnName(@"RunCount").HasColumnType("int").IsRequired();
            Property(x => x.IsFavorite).HasColumnName(@"IsFavorite").HasColumnType("bit").IsRequired();
        }
    }

    #endregion

}
// </auto-generated>

